{% set name = "azure-synapse-artifacts" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3ed6c142faf62d3191a943b3222547f7730d4cbc10355d17d64fa77e0421644a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.6.0
    - python >={{ python_min }}
    - isodate >=0.6.1
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

test:
  imports:
    - azure.synapse.artifacts
    - azure.synapse.artifacts.aio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Synapse Artifacts Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://azure.github.io/azure-sdk-for-python/synapseanalytics.html

extra:
  recipe-maintainers:
    - xylar
